---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tmtro/public_html/wp-content/
    - /bin/mkdir -p $DEPLOYPATH/themes $DEPLOYPATH/plugins
    - /bin/rsync -av themes/martfury-child/ $DEPLOYPATH/themes/martfury-child/
    - /bin/test ! -d plugins || /bin/rsync -av --include='tmt-*/' --include='tmt-*/**' --exclude='*' plugins/ $DEPLOYPATH/plugins/
